portal/urls.py
from django.conf.urls import url
from portal.views import home

urlpatterns = [
	url(r'^$', home),
]

titube/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^portal/', include('portal.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Video(models.Model):
	titulo = models.CharField(max_length=250)
	video = models.FileField(null=True, blank=True)
	imagem = models.FileField(null=True, blank=True)
	categoria = models.ForeignKey("Categoria", on_delete=models.CASCADE, null=True)

	def __unicode__(self):
		return u'%s' %(self.titulo)


class Categoria(models.Model):
	titulo = models.CharField(max_length=250)


	def __unicode__(self):
		return u'%s' %(self.titulo)

portal/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from portal.models import Categoria, Video



def home(request):

	#categorias = Categoria.objects.filter(titulo__in=("Windows","Acompanhamento de Sessão"))

	categorias = Categoria.objects.filter(titulo__in=("Windows","Acompanhamento de Sessão"))	

	context = {
			"categorias":categorias
	}

	template  = loader.get_template('portal/home.html')
	return HttpResponse(template.render(context, request))

portal/templates/portal/home.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Css menu de navegacao</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sintony" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <script type="text/javascript">

    </script>

</head>
<body>

    <div class="header-wrap">
        <ul>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">Notícias</a></li>
            <li><a href="#">Portais</a></li>
            <li class="last-option"><a href="#">Adm</a></li>   
            <li class="icon"><a href="#">&#9776;</a></li>
        </ul>        
    </div>

    <div class="main-wrap">
    

        <!--Fazer widget lateral de categoria-->
        <div class="main-content">
            <input type="text" name="search" placeholder="categoria">
            {% for categoria in categorias %}

                <div class="category-wrap">
                    <h2 class="category-tittle">{{ categoria.titulo }}</h2>
                    {% for vid in categoria.video_set.all %}
                        <div class="card">
                            <a class="img-card" href="#">
                                <img src="{{ vid.imagem.url }}">
                            </a>
                        
                            <div class="card-content">
                                <h4 class="card-title">
                                    <a href="#">
                                        {{ vid.titulo }}
                                    </a>
                                </h4>
                            </div>
                        </div>
                    {% endfor %}
                <p>BOTAO</p>
                </div>

            {% endfor %}

        </div>

    </div>


    <script type="text/javascript">

        function hide_first_three(value)
        {
            console.log(value)
        }


        function get_all_category_wrappers(){
          var all_category_wrappers = document.querySelectorAll(".category-wrap")
          for(i=0; i< all_category_wrappers.length; i++){
              var wrap = all_category_wrappers[i]
              var all_child_cards = wrap.querySelectorAll(".card")
          }
        }

        get_all_category_wrappers()

    </script>

</body>
</html>